name: Metronome
description: A simple metronome app

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^0.5.2
  cupertino_icons: ^0.1.0
  flutter_launcher_icons: ^0.5.2
  path_provider:
  quiver:
  recase:

flutter_icons:
  android: true
  ios: "Beet-Icon"
  image_path: "assets/beet.png"
  image_path_android: "assets/beet.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/