name: metronome
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  audioplayer: ^0.5.0
  path_provider:
  quiver: '>=0.29.0 <0.30.0'
  recase:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true